apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: default
spec:
  project: default
  source:
    chart: dev
    repoURL: https://github.com/DavidGitter/argocd-helm-test.git
    targetRevision: HEAD
    path: template
  destination:
    server: https://kubernetes.default.svc
    namespace: argodeploy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

#argocd commands
# kubectl create namespace argocd
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# kubectl get all -n argocd
# kubectl port-forward svc/argocd-server -n argocd 8080:443
# kubectl get secret -n argocd argocd-initial-admin-secret -o yaml 
# kubectl apply -f argocd-app.yaml