apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: default
spec:
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: deploy.route.tls.enabled
          value: "true"
    chart: helm-test
    repoURL: https://github.com/DavidGitter/argocd-helm-test/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argodeploy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true